name: polymer_dart_samples
description: Port of https://github.com/PolymerLabs/polymer-snippets
dependencies:
  polymer: ">=0.13.0 <0.14.0"
transformers:
- polymer:
    entry_points: [
        web/basics/binding_to_a_field/index.html,
        web/forms/binding_to_a_text_input/index.html]
environment:
  sdk: ">=1.2.0 <2.0.0"
